[code]
editor = 'vim'
lang = 'golang'

[cookies]
csrf = 'AkekIh9ODyQfMQwO7qKwBK5mxOCDCDpAi7GBvkfv6ZSe5n7unsGs597hbBvZmRLs'
session = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiMTE4OTYxNDYiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6ImI4MmQxOTU5M2E2YjRlMzFkNDNkYWQzYjJmZmE3NTRjNTMxZTZhOTU3MDkyMWExZWFhZjM4MzIxNGQ4ZDFmOTQiLCJpZCI6MTE4OTYxNDYsImVtYWlsIjoiYnVpaGFjaGkubmlzaGlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ2OHl0ZSIsInVzZXJfc2x1ZyI6InY4eXRlIiwiYXZhdGFyIjoiaHR0cHM6Ly9hc3NldHMubGVldGNvZGUuY29tL3VzZXJzL2RlZmF1bHRfYXZhdGFyLmpwZyIsInJlZnJlc2hlZF9hdCI6MTcwNDE1NjYxNywiaXAiOiIxMTMuNDMuMTQyLjIzOCIsImlkZW50aXR5IjoiNGJlNTA3NTgyNGRmYzllYmZjZWE5NjJmMzE4ODA5N2MiLCJzZXNzaW9uX2lkIjo1MjY3NzU4OCwiX3Nlc3Npb25fZXhwaXJ5IjoxMjA5NjAwfQ.x7nykoWfLJ2KOaGIgBJ2NWMyqVJiqA7SQ2kE4v-UWF8'

[storage]
cache = 'Problems'
code = 'code'
root = '~/.leetcode'
scripts = 'scripts'
